# Generated by Django 4.2 on 2023-04-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_nacimeinto',
            new_name='fecha_nacimiento',
        ),
    ]
